plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/brendan/Desktop/shamrock-active-software/shamrock-bail-portal-site/netlify-embeds"
publishOrigin = "default"
base = "/Users/brendan/Desktop/shamrock-active-software/shamrock-bail-portal-site/netlify-embeds"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]